version: "3.7"
services:



  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
            - /:/host:ro,rslave
    command: 
            - '--path.rootfs=/host'
            - '--path.procfs=/host/proc' 
            - '--path.sysfs=/host/sys'
            - --collector.filesystem.ignored-mount-points
            - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: unless-stopped




  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter
    restart: unless-stopped
    ports:
     - 9121:9121
    environment:
      REDIS_ADDR: "redis:6379"
#      REDIS_USER: null
#      REDIS_PASSWORD: my_master_password



  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    restart: unless-stopped
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://test:172.16.4.202:5432/test?sslmode=disable"

#      - DATA_SOURCE_URI=172.16.4.202:5432/postgres?sslmode=disable
#      - DATA_SOURCE_USER=postgres
#      - DATA_SOURCE_PASS=password






  cadvisor:
    image: 'google/cadvisor:latest'
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk/:ro
    ports:
    - '8080:8080'




